name: Matrix Test & Docker Build
on:
  push:
    branch: main

jobs:
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test with matrix
      strategy:
        matrix:
          python-version: ['3.9', '3.10', '3.11']
          os: [ubuntu-latest, windows-latest]

    - name: docker-login
      needs: Test with matrix
      runs-on: ubuntu-latest
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/aw714797-lang/my-app:latest

